### ISSUE TITLE
建议在后面附带上明显的Markdown标签

### ISSUE THREAD

**Issue by whatwewant** [ruanyf/document-style-guide#1]
建议在后面附带上明显的Markdown标签, 一直喜欢用md写文档，阮老师的规范得好好看，都是经验，非常感谢。

**Comment by whatwewant** [comment]
像Airbnb的规范，正确和错误都出来，非常直观，这才是矫正文档的好文档。

**Comment by ruanyf** [comment]
“Markdown 标签”是什么意思？

**Comment by whatwewant** [comment]
指的是 我个人喜欢用markdown也文档 将您的规范用markdown实现 这对我们开发来说方便很多

**Comment by ruanyf** [comment]
原来是这个意思……

其实，我想过写一个 Chrome 的扩展，自动检查 markdown 文件的风格。

**Comment by whatwewant** [comment]
好吧 原来是这个想法 我最近也想写Chrome插件。。
