### ISSUE TITLE
一个小疑问

### ISSUE THREAD

**Issue by zhaotoday** [ruanyf/document-style-guide#12]
做前端的经常谈到浏览器兼容性问题，这时候我们会说：IE 8 以上或者 IE 8+。
这时候会有歧义，是否包含 IE 8 在内。
这种情况怎么解决？

**Comment by ruanyf** [comment]
有两种表示方法，一种是明确表达语义，还有一种用括号进一步说明。

```
方法一：浏览器最低支持 IE8。

方法二：浏览器支持 IE8+（含 IE8）
```

我个人比较影响第二种说法。
