### ISSUE TITLE
阮老师怎么看待用 asciidoc 来写书?

### ISSUE THREAD

**Issue by Akagi201** [ruanyf/document-style-guide#14]
最近计划写书, 打算用 asciidoc 写原稿, word 交付出版社.

然后, 来到这里把相关规范重新又读了一遍.

想看看 阮老师对 asciidoc 的看法, 因为, 好像阮老师的书都是 markdown 的. 之前有考虑过用 asciidoc 吗?

我个人觉得 asciidoc 跟 markdown 很类似, 而且功能更加丰富, 并且, 像 o'reilly 这种出版社还官方推荐 asciidoc. 想听听阮老师看法.

**Comment by ruanyf** [comment]
我没用过 asciidoc，但是知道很多人推荐它。我觉得可以试试。

我选择 Markdown，主要因为工具丰富，后期处理方便。
