### ISSUE TITLE
标题与加粗的选择

### ISSUE THREAD

**Issue by Jay54520** [ruanyf/document-style-guide#16]
什么情况下使用标题，什么情况下使用加粗，是否存在选用两者都合适的情况？
比如在[以太坊白皮书](https://github.com/ethereum/wiki/wiki/White-Paper)中，有
> * **Namecoin** - created in 2010,

换用 
> #### Namecoin
> Created in 2010,

是否也合适？

**Comment by ruanyf** [comment]
换用后的形式比较好。

正文里面的一级分类标题，才建议加粗。

```markdown
# 一级标题
## 二级标题
### 三级标题

**（1）小标题**
```
