### ISSUE TITLE
文档规范的根据是什么？

### ISSUE THREAD

**Issue by Jay54520** [ruanyf/document-style-guide#17]
比如
> 全角中文字符与半角阿拉伯数字之间，有没有半角空格都可，但必须保证风格统一，不能两种风格混杂。 -- https://github.com/ruanyf/document-style-guide/blob/master/docs/text.md

这里的依据是**风格统一**。

那么以下的根据是什么？美学吗？
> 英文单位若不翻译，单位前的阿拉伯数字与单位间不留空格。
>错误：一部容量为 16 GB 的智能手机
>正确：一部容量为 16GB 的智能手机

当遇到文档中没有说明的或者模棱两可的情况，我们该依据什么来选择？

**Comment by ruanyf** [comment]
因为单位与数字是一体的，不留空格可以保证阅读的流畅。

如果数字比较重要的话，建议在中文之间留一个空格。如果数字不需要强调，可以不留。
