### ISSUE TITLE
当引用部分复杂时，如何引用并评论？

### ISSUE THREAD

**Issue by Jay54520** [ruanyf/document-style-guide#18]
在 MarkDown 中，可以使用 `>` 来表示引用，在引用部分是整段文字的时候，使用 `>` 没有什么问题。但是当引用部分含有多个段落及样式的时候，就难以引用，比如我引用下面的内容，并加入我自己的评论，如何做会比较好？

引用自：https://github.com/ruanyf/document-style-guide/edit/master/docs/paragraph.md
引用第三方内容时，应注明出处。

```
One man’s constant is another man’s variable. — Alan Perlis
```

如果是全篇转载，请在全文开头显著位置注明作者和出处，并链接至原文。

```
本文转载自 WikiQuote
```

使用外部图片时，必须在图片下方或文末标明来源。

```
本文部分图片来自 Wikipedia
```

**Comment by ruanyf** [comment]
引用部分不建议包含样式。

如果需要插入评论，最好是将引用拆开，显式加入评论。

请看下面的例子。

```
> 长句 A。长句 B。
```

现在需要在两个句子之间，插入一个评论。

```
> 长句 A。

对于上面的句子，我认为，……

原作者继续写道：

> 长句 B。
```
