### ISSUE TITLE
读书笔记的写作规范

### ISSUE THREAD

**Issue by Jay54520** [ruanyf/document-style-guide#19]
读书笔记的定义：对于一篇文章的某些段落或句子甚至词汇，想写下自己的一些东西。

文章原文会占据绝大部分，而读书笔记可能并不多。那么还要对文章原文进行 “`>`” 引用吗？还是不引用文章原文，而着重强调读书笔记？

**Comment by ruanyf** [comment]
规范是针对技术文档的。

如果是个人使用的读书笔记，可以完全按照个人的习惯写，这个规范只是参考。
