### ISSUE TITLE
数值与中文单位之间是否要加空格？

### ISSUE THREAD

**Issue by ruanyf** [ruanyf/document-style-guide#2]
第一组

```
A. 体重是 68公斤。
B. 体重是 68 公斤。
```

第二组

```
A. 今年是 2016年。
B. 今年是 2016 年。
```

第三组

```
A. 今天是 9月 1日。
B. 今天是 9 月 1 日。
```

第四组

```
A. 现在是 8点 36分。
B. 现在是 8 点 36 分。
```

上面四种情况，A 句是数字与中文单位之间没有空格，B 句是有空格。大家觉得，哪种写法比较可取？

**Comment by sepmein** [comment]
一、A
二、A
三、9月1日
四、8点36分

**Comment by zlx** [comment]
有空格更好一些：https://github.com/sparanoid/chinese-copywriting-guidelines#%E4%B8%AD%E6%96%87%E8%88%87%E6%95%B8%E5%AD%97%E4%B9%8B%E9%96%93%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC

**Comment by 1100100** [comment]
A更合适，看着更顺眼；好像没见过B句的风格

**Comment by MofeLee** [comment]
我觉得A，如果要读出这个句子，A明显更合适

**Comment by 4lan5** [comment]
完全没有空格看着更舒服点吧

**Comment by dada99** [comment]
数字和字母与中文之间有空格更舒服。

**Comment by coolgod** [comment]
A
A
B
B

**Comment by ClassName** [comment]
A组更好，B组的数字与单位有割裂感，下面的日期最好放一起，整体感更强

**Comment by cyseria** [comment]
B

**Comment by pythias** [comment]
1. A
2. A
3. 今天是10月18日
4. 现在是9点54分

**Comment by ByWhy** [comment]
如果没有特殊要求，完全没有空格感觉可以，如果有，那就数字两边都有空格

**Comment by tranch-xiao** [comment]
1. B
2. B
3. B
4. B

要么完全不带空格，所有备选答案左边都预留了空格，可见你自己内心还是倾向于带空格的。

**Comment by StoneFu2015** [comment]
带空格，突出数字！！！

**Comment by haaaiiimmm** [comment]
以上都选B。
不过为什么没有这种？「今天是10月18号。」
要空格就左右两边都空，或者都不空。个人倾向于两边都没空格。

**Comment by riophae** [comment]
个人习惯是尽可能加空格。除非当数字和相邻的部分是不可分割的一部分，才考虑不加空格。

**Comment by catbaron-** [comment]
中文英文/中文数字混排的时候，英文和数字两边加空格是因为英文与数字字符的宽度比较小，实际上在其两边添加英文空格是合适的，如果添加中文空格则过于分散了。而且感觉也没有用空格表示强调的用法。如果要强调，就用加黑或者MD的反引号。

**Comment by zombieJ** [comment]
感觉A顺眼一点，不过看讨论。似乎空格更合理？

**Comment by fakefish** [comment]
要么都加空格要么都不加空格。。
选B

**Comment by clinyong** [comment]
选 B

**Comment by zhangciwu** [comment]
其实word处理的最好，输入的时候没有空格，显示的时候前后各有半个空格的样子，
所以这个应该交给浏览器或者CSS才对
（去给CSS提issue或者feature如何）

**Comment by iphyer** [comment]
支持，要么都空，要么都不空。
不过从全局考虑，选择都空，也就是B。
主要是这样的，现在是数字，阿拉伯数字的话都空的话可以方便大家扫描看过去。因为你知道这儿是数字，其实可以跳过去不看。
同时方便做匹配。
这也和英文保持对应，英文也都空。

**Comment by kemingcao** [comment]
如果按照文档来说的话，我倾向于都是B，数值应该需要醒目，看着舒服的话反而会忽略。就比如`NeXT `。

**Comment by cbk808** [comment]
日期一般用的很少， 8:36 2016-10-18 这样不也很好吗，68kg, 反正阿拉伯数字也是外来的，不差几个英文字母

**Comment by hanzichi** [comment]
B，习惯加空格后 A 实在看不下去 ...

**Comment by leveme** [comment]
B，文档一直用这种格式

**Comment by ever-rhythm** [comment]
当文本中需要强调 数字，且数字后面单位和数字倾向于1组整体时，可以采用前面空格，后面连续的写法。当需要强调整个词时，可以采用 前面空格，中间连续，后面空格 的写法。

例如

今年是 2016年
小明获得了第 1 名的好成绩

**Comment by gokure** [comment]
B，在排版上跟全角视觉上统一
```
全角：今天是９月１日。
半角带空格：今天是 9 月 1 日。
半角不带空格：今天是9月1日。
```

**Comment by jingsam** [comment]
我支持B，即所谓的盘古之格或逼格。其实这本不该由作者来加空格，而是应该由排版引擎自动生成，但是广大前端程序员根本没意识到这个问题，所以只好由作者给他们擦屁股。

**Comment by zhangchunlin** [comment]
我的习惯是数字和中文连用不加空格,但是英文单词和中文连用要加空格

**Comment by iAbu** [comment]
要么两边都加，要么都不加吧。个人习惯不加。记得之前的微信公众号后台，如果字与字之间加空格，前端显示是自动另起一行的，简直要死人命。不知道现在改进了没有。

**Comment by oakfire** [comment]
技术文档的数字基本都属于需要“强调”的地方，都加空格比较好。可参考各个大厂商（比如苹果）的中文文档。

**Comment by showzeng** [comment]
可参阅：[文案风格指南](https://open.leancloud.cn/copywriting-style-guide.html)

**Comment by deacyn2013** [comment]
今年是 2016 年
今年是2016年

这段话第一句显然是更好看的，但是读起来会有膈应。第二局读起来更为通顺！

**Comment by wuanunet** [comment]
四種都是 B，中文遇到數字跟英文時，前後都習慣加上空格。

**Comment by Huige2012** [comment]
A. 今天是2016年9月 1日。
B. 今天是 2016 年 9 月 1 日。

虽然差别不大，但也听明显的，前后加上空格读起来更明朗些。

**Comment by kael777** [comment]
AAAA

**Comment by ruanyf** [comment]
我想了想，能不能分成两种情况。

表示数量含义时，数字与中文单位之间一律加空格。

```
这件商品的价格是 1000 元。
```

表示时间时，数字前后一律不加空格。

```
现在是2016年9月1日8点14分。
```

这样规定，大家觉得可以接受吗？

**Comment by zhuangya** [comment]
`体重是68公斤，今年是2016年9月1日8点36分42秒`

这样有啥问题

**Comment by jingsam** [comment]
>有研究顯示，打字的時候不喜歡在中文和英文之間加空格的人，感情路都走得很辛苦，有七成的比例會在 34 歲的時候跟自己不愛的人結婚，而其餘三成的人最後只能把遺產留給自己的貓。畢竟愛情跟書寫都需要適時地留白。 — vinta/paranoid-auto-spacing

**Comment by 1100100** [comment]
不知道老师您倾向于给数字和中文之间加空格是为了什么呢?

数字和英文之间加空格是为了易读, 不加空格会影响阅读。比如：
易读: 1,000 rows
难读: 1,000rows

但数字和中文之间加了空格反而看着不顺眼。比如
易读: 是1000元
难读: 是 1000 元

**Comment by zhuangya** [comment]
> 有研究顯示，打字的時候不喜歡在中文和英文之間加空格的人，感情路都走得很辛苦，有七成的比例會在 34 歲的時候跟自己不愛的人結婚，而其餘三成的人最後只能把遺產留給自己的貓。畢竟愛情跟書寫都需要適時地留白。 — vinta/paranoid-auto-spacing

跑题了

**Comment by zhangciwu** [comment]
http://help.dottoro.com/lcrgkpao.php

**Comment by jingsam** [comment]
@zhangciwu 这也从侧面说明中西文之间要加空格了，所以问题不在于要不要加，在于由谁来加：是作者还是排版引擎。现阶段只能由作者代劳了

**Comment by haohailong** [comment]
选 B，因为这里空格的理由并不是分词，而是中西文的分隔。举例来说，按照分词逻辑第一个例子该写成「体重 是 86公斤。」

**Comment by jingsam** [comment]
@haohailong 海龙大哥好，我记得您有一集播客已经讲了这个问题，所以不要再纠结要不要加空格了，结论就是要加。

**Comment by hotcha** [comment]
B B B B

**Comment by niinaranpo** [comment]
空格在这里是没有语义的，仅仅是作为分隔，那么这个分隔就不应该由用户输入应该交给排版引擎／浏览器／前端来加，而且应该比普通的空格更窄（比如 en 空格），以避免打断整个句子。

**Comment by haohailong** [comment]
@niinaranpo 目前浏览器/前端基本上会忽视这一点，而且这个空格严格讲并不是没有语义的，只是介于有语义和无语义之间。

**Comment by lchad** [comment]
又不是代码，没必要前后都是空格吧

**Comment by haohailong** [comment]
@lchad 1. 数字本身是西文，空格本身是西文属性的一部分。2. 中西文之间添加空格过渡会更平滑。3. 最好的解决方案其实是前后各添加 1/4 个全角空格，但在现在的互联网环境下并不现实。考虑到前两个原因，添加空格比不添加更为可取。

**Comment by HappyHackingNinja** [comment]
* [為什麼你們就是不能加個空格呢？](https://github.com/vinta/pangu.js)

**Comment by woosley** [comment]
个人觉得没有空格的必要

- 阿拉伯数字在中文中本身就有重点突出的效果
- 要么前后都有，要么都没有，前或后一个空格太难看。

**Comment by PeterYur** [comment]
数字本身没有属性，跟随主文

中文没有空格，加空格不符合中文习惯，且存在被修改（如空格处套打加个1，无法识别）可能，目前据我所阅读的比较正式的文件、法律文书等，未见加空格的。

西文包含空格，加空格是书写和阅读习惯，如前述若被套打容易识别。

**Comment by haohailong** [comment]
数字属于「西文」的一种，并非没有「属性」

**Comment by ruanyf** [comment]
看来这个问题没有共识，那就暂时关闭这个 issue。

还是保持原样，建议在阿拉伯数字前后加上一个半角空格。

**Comment by javaee-8** [comment]
建议在阿拉伯数字前后加上一个半角空格。
但是在遇到换行时可以适当调节，比如多一个空格可能会造成数字部分换行，不易阅读。
内容与排版需要结合在一起，不能孤立分析，还需要考虑是否用于打印，黑白打印有黑白打印的办法，彩色打印有彩色打印的办法。

**Comment by angellaugh** [comment]
1.B;
2.B;
3.A;
4.A;

**Comment by SunshineLXH** [comment]
感觉主要还是保持一个对称吧，要求前后都有空格，要么都没有

**Comment by zhangchunlin** [comment]
我觉得用纯中文不用英文单词一样能用阿拉伯数字,阿拉伯数字归类到英文比较奇怪.

**Comment by slimsymphony** [comment]
因为字符宽度，英文数字混写添加空格比较自然，中文和数字混写添加空格，感觉多出无意义的分割空间，分散阅读注意力，建议前后都不要添加

**Comment by zhangyiluo** [comment]
1. B
2. B
3. B
4. B

比如第 4 个，阅读 “ 现在是 8点 36分” 我个人觉得从视觉上，会先连个数字单位 “ 点 ” 都看在眼内，然后再回头读数字 “ 8 ” 。而阅读 ” 现在是 8 点 36 分 “ 就是顺着读下去，不用返回头。

**Comment by gymgle** [comment]
我的习惯是把数字当成英文一样，前后都加空格，所以更习惯下面这种，否则强迫症表示很难受：
```
B. 体重是 68 公斤。
B. 今年是 2016 年。
B. 今天是 9 月 1 日。
B. 现在是 8 点 36 分。
```

**Comment by liangzr** [comment]
@ruanyf 示例有些问题，在等宽字体下，B 似乎有割裂感，而我们日常情景并不是等宽字体，如果再做次对比：


| 组    | 等宽字体                              | 非等宽字体                         |
| :---: | :-------------------------------- | :---------------------------- |
| 第一组  | `A. 体重是 68公斤。`<br>`B. 体重是 68 公斤。` | A. 体重是 68公斤。<br>B. 体重是 68 公斤。 |
| 第二组  | `A. 今年是 2016年。`<br>`B. 今年是 2016 年。` | A. 今年是 2016年。<br>B. 今年是 2016 年。 |
| 第三组  | `A. 今天是 9月 1日。`<br>`B. 今天是 9 月 1 日。` | A. 今天是 9月 1日。<br>B. 今天是 9 月 1 日。 |
| 第四组  | `A. 现在是 8点 36分。`<br>`B. 现在是 8 点 36 分。` | A. 现在是 8点 36分。<br>B. 现在是 8 点 36 分。 |

所以我选 B，一定都得左右加空格 2333

**Comment by ruanyf** [comment]
现在定下的标准是可以加，也可以不加。下面两种写法都正确。

```
// 写法一
体重是 68 公斤。

// 写法二
体重是68公斤。
```
