### ISSUE TITLE
小数部分不应使用千分撇

### ISSUE THREAD

**Issue by NateScarlet** [ruanyf/document-style-guide#26]
https://github.com/ruanyf/document-style-guide/blob/f11132b36c3041b582a13093df9ff62951885ae7/docs/number.md#%E5%8D%83%E5%88%86%E5%8F%B7

参见:

《中华人民共和国国家标准 GBT 15835-2011 出版物上数字用法的规定》5.1.1 多位数

https://zh.wikipedia.org/wiki/%E5%B0%8F%E6%95%B8%E9%BB%9E#cite_ref-GB15835_1-1
http://www.std.gov.cn/gb/search/gbDetailed?id=71F772D7DA87D3A7E05397BE0A0AB82A

**Comment by ruanyf** [comment]
谢谢指出，应该更正。
