### ISSUE TITLE
建议货币类型使用ISO 4217标准

### ISSUE THREAD

**Issue by liuhu** [ruanyf/document-style-guide#28]
"数值"章节中的"千分号"这一小节里举了一个例子：
`XXX 公司的实收资本为 RMB1,258,000。`
其中货币类型 `RMB` 替换为 `CNY` 更符合规范。

参考：
- [ISO_4217标准](https://en.wikipedia.org/wiki/ISO_4217)
- [知乎讨论](https://www.zhihu.com/question/19904144)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
