### ISSUE TITLE
关于“英文单位若不翻译，单位前的阿拉伯数字与单位间不留空格”

### ISSUE THREAD

**Issue by tianyikillua** [ruanyf/document-style-guide#35]
根据[国际单位制的标准 5.4.3](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf)，数字与单位之间还有需要一个空格的，这个空格理解成数字与标点之间的乘法。唯一的例外是表示角度的度、角和分。

同样，[GB 3100-1993 国际单位制及其应用 6.2.4](https://zh.wikisource.org/zh-hans/GB_3100-1993_%E5%9B%BD%E9%99%85%E5%8D%95%E4%BD%8D%E5%88%B6%E5%8F%8A%E5%85%B6%E5%BA%94%E7%94%A8) 规定了

> 单位符号应写在全部数值之后，并与数值间留适当的空隙。

所以在没有比如 CSS 样式处理“空隙”的情况下，在数字与单位间还是得加上一个空格。

**Comment by ruanyf** [comment]
谢谢指出，已经改正了。
