### ISSUE TITLE
为什么更建议使用连接线来分隔文件名中多个单词呢

### ISSUE THREAD

**Issue by shinny-limin** [ruanyf/document-style-guide#37]
在[文件名](https://github.com/ruanyf/document-style-guide/blob/master/docs/structure.md#%E6%96%87%E4%BB%B6%E5%90%8D)中有：

> 文件名包含多个单词时，单词之间建议使用半角的连词线（-）分隔。

请问为什么更建议使用连接线来分隔文件名中的多个单词呢？

**Comment by ruanyf** [comment]
1）有的单词包含连词线，如果使用下划线，不利于统一风格，比如 five-year_child。

2）下划线需要按 Shift 键。

3） 下划线不利于 SEO。https://www.woorank.com/en/blog/underscores-in-urls-why-are-they-not-recommended
