### ISSUE TITLE
英文省略号可否使用？

### ISSUE THREAD

**Issue by yi-Xu-0100** [ruanyf/document-style-guide#41]
英文中，省略号是`...`，如果是中英文混排中，是否应该保留英文省略号？如：

> 1. 下面是一句不完全的引用：“This is an incomplete quote ...omitted in the middle.”。
> 2. 下面是一句不完全的引用：“This is an incomplete quote omitted in the end....”。
> 3. 下面是一句不完全的引用：“...is an incomplete quote omitted in the head.”。

这三句的英文省略号分别在段中、端末和段首。而且是在引用中，是否应该遵循英文规范而保留省略号。

文章中 [标点符号 -- 省略号](https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md#%E7%9C%81%E7%95%A5%E5%8F%B7) 未提及英文省略号的使用，我有点不确定在中英文混排中，是否应该保留。还是说，应该规避这样的写法。

**Comment by ruanyf** [comment]
引用的英文段落中，应该使用英文标点，而不是中文的。

这样既可以尊重原文，也可以保持视觉效果一致。中文标点只适于使用中文表达的段落。
