### ISSUE TITLE
推荐工具：lint-md

### ISSUE THREAD

**Issue by hustcc** [ruanyf/document-style-guide#47]
lint-md 是基于阮老师的文档规范来的，将其中一些规则直接工具 lint 化。组织地址：https://github.com/lint-md

 - [x] lint-md 提供 lint、fix 的核心 API
 - [x] cli 命令行工具
 - [x] eslint 扩展
 - [x] vscode 副局插件

阮老师可以看看，然后给个推荐呗~

**Comment by ruanyf** [comment]
你发到[周刊的讨论区](https://github.com/ruanyf/weekly/issues)，我再发到周刊上面。
