### ISSUE TITLE
两章节连接号说明不一致和参考链接优化建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [ruanyf/document-style-guide#49]
1. 《数值》一节的 [数值范围](https://github.com/ruanyf/document-style-guide/blob/master/docs/number.md#数值范围) 部分中的说明

	>  表示数值范围时，用 `～` 或 `——` 连接

	和《标点符号》一节的 [连接号](https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md#连接号) 部分中的说明

	> 数值范围（例如日期、时间或数字）应该使用波浪连接号（`～`） 。

	两处的说明并不一致。应该统一这两处的说明。

	而且根据现行最新国家标准 GB/T15834-2011 [《标点符号用法》](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=22EA6D162E4110E752259661E1A0D0A8)：

	> 4.13.3.2 标示下列各种情况，一般用一字线，有时也可用浪纹线：
	> ……
	> b) 标示数值范围（由阿拉伯数字或汉字数字构成）的起止。
	> 示例 4：25～30 g
	> 示例 5：第五～八课

	并无用两个 `—`（U+2014 Em Dash）标示数值范围的起止的用法。

2. 为什么要往 [参考链接](https://github.com/ruanyf/document-style-guide/blob/master/docs/reference.md) 中添加两个《出版物上数字用法》（即 [PDF 版](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091154536.pdf) 和 [百度百科词条](https://baike.baidu.com/item/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E5%AE%B6%E6%A0%87%E5%87%86%E5%87%BA%E7%89%88%E7%89%A9%E6%95%B0%E5%AD%97%E7%94%A8%E6%B3%95)）？
个人认为没必要。而且该百度百科词条的连名称都是错的，虽然标准号写着是 GB/T 15834-2011，但内容是不完全一致的。
如果是希望能直接在线预览，完全可以随便在百度文库里找一个，或者直接用国家标准全文公开系统的 [在线预览](http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=F5DAC3377DA99C8D78AE66735B6359C7)。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
