### ISSUE TITLE
建议规范英文逗号和中文顿号的用法

### ISSUE THREAD

**Issue by xcatliu** [ruanyf/document-style-guide#5]
这个出现的频率比较高，并且使用方式有争议，大家可以讨论下

中文和中文之间使用中文顿号，这个应该没争议

A. 英文和英文之间使用英文逗号
B. 英文和英文之间使用中文顿号
C. 以上皆可

```
使用的技术包括 JavaScript, CSS 和 HTML
使用的技术包括 JavaScript、CSS 和 HTML
```

X. 英文和中文之间使用英文逗号
Y. 英文和中文之间使用中文顿号
Z. 以上皆可

```
我最欣赏的科技公司有 Google, Facebook, 腾讯和阿里等
我最欣赏的科技公司有 Google、Facebook、腾讯、阿里和百度等
```

**Comment by xcatliu** [comment]
我个人倾向于 A 和 Y

**Comment by ruanyf** [comment]
大家能不能同意这个原则：中文句子应该使用全角符号？

理由：这样可以保证视觉的一致。

---

我因此建议下面的做法：

1、中文句子中，并列词语之间使用全角顿号，即使并列的成分是英语词汇也是如此。

```
我最欣赏的科技公司有 Google、Facebook、腾讯、阿里和百度等。
```

2. 英文句子中，并列词语之间使用半角逗号。

```
The tech companies I appreciated most are Google, Facebook, Tencent, AliBaBa, and Baidu. 
```

**Comment by xcatliu** [comment]
可能的取值有 `immutable`、`request`、`request-no-cors`、`response` 或 `none`
可能的取值有 `immutable`, `request`, `request-no-cors`, `response` 或 `none`

包含 map、filter、invoke、reduce、template、throttle、bind、extend、pick、clone 等众多方法
包含 map, filter, invoke, reduce, template, throttle, bind, extend, pick, clone 等众多方法

使用 `<article>`、`<aside>`、`<footer>`、`<header>`、`<nav>` 和 `<section>` 布局
使用 `<article>`, `<aside>`, `<footer>`, `<header>`, `<nav>` 和 `<section>` 布局

提供一些案例

**Comment by ruanyf** [comment]
中文句子包含英文词汇，但这还是一句中文，要遵守中文标点的规则。

所以，我认为，这时不宜采用半角逗号代替全角顿号。

**Comment by zhanghuajie** [comment]
ok
