### ISSUE TITLE
请问一下文件名的话，下划线和连字符的差别，以及关于冒号这类符号的转变方式

### ISSUE THREAD

**Issue by realliyifei** [ruanyf/document-style-guide#51]
对于文件名（全英文小写），下划线`_`和连字符`-`有啥优劣？（看了您的[为什么文件名要小写？ - 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2017/02/filename-should-be-lowercase.html)）

以及，如果一个原文件名是`A Guide: aaa bbb ccc`，那应该如何转变好？我暂时用的是`a-guide_aaa-bbb-ccc`但好像有点奇怪？

**Comment by ruanyf** [comment]
建议一律使用连词线，统一风格。

连词线比下划线，可以少按一个 Shift 键。
