### ISSUE TITLE
讨论：列表末尾的符号应该是“无”、“分号”还是“句号”？

### ISSUE THREAD

**Issue by imageslr** [ruanyf/document-style-guide#52]
如题。对于以下段落，大家觉得哪种表现形式更好？

---

无标点，只适用于一行中没有句号的情况：

- 一个段落只能有一个主题，或一个中心句子
- 段落的中心句子放在段首，对全段内容进行概述。后面陈述的句子为核心句服务
- 段落之间使用一个空行隔开
- 段落开头不要留出空白字符

---

分号，最后一行句号：
- 一个段落只能有一个主题，或一个中心句子；
- 段落的中心句子放在段首，对全段内容进行概述。后面陈述的句子为核心句服务；
- 段落之间使用一个空行隔开；
- 段落开头不要留出空白字符。

---

每行都是句号：
- 一个段落只能有一个主题，或一个中心句子。
- 段落的中心句子放在段首，对全段内容进行概述。后面陈述的句子为核心句服务。
- 段落之间使用一个空行隔开。
- 段落开头不要留出空白字符。

**Comment by litianqi1996** [comment]
虽然我比较喜欢第一种方式，但是目前都是用的第三种 。

**Comment by imageslr** [comment]
> 虽然我比较喜欢第一种方式，但是目前都是用的第三种 。

我一般是用第一种，前提是列表的每一行都没有句号，但是可以有分号。

如果某一行必须有句号，那我就使用第二种或者第三种。

**Comment by ruanyf** [comment]
如果其中一行内部有句号，每一行结尾应该都使用句号。

结尾无标点，或者使用分号，都说不通。

**Comment by wenyuan** [comment]
* 我个人的话，通常使用第三种（每一行结尾都使用句号）。
* 在每行很短、只是词语或短语的情况下会使用第一种（无标点）。
