### ISSUE TITLE
文档体系中的链接失效

### ISSUE THREAD

**Issue by Popxie** [ruanyf/document-style-guide#53]
> 下面是两个真实范例，可参考。
>
> - Redux 手册
> - Atom 手册

 Atom 手册 链接有问题 无法访问
![04](https://user-images.githubusercontent.com/24952644/127734459-a35d51af-b0b8-4ca3-8d8f-f3cf462b103b.jpg)

**Comment by ruanyf** [comment]
我可以访问，是不是被墙了。
