### ISSUE TITLE
参考链接中有失效的链接

### ISSUE THREAD

**Issue by nn6v6nn** [ruanyf/document-style-guide#57]
文件 docs/reference.md
失效项目：产品手册中文写作规范, by 华为
失效链接：https://wenku.baidu.com/view/23cc1a6527d3240c8447efbf.html
提示该文档已被删除。
建议替代链接：
https://www.taodocs.com/p-51273.html
https://www.jinchutou.com/p-109416385.html

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
