### ISSUE TITLE
建议添加中英文混排说明

### ISSUE THREAD

**Issue by xianghongai** [ruanyf/document-style-guide#75]
1. 英文名词，首字母大写；
2. 英文单词左/右有全角中文，用半角空格隔开，如果是全角标点符号则不用；
3. 操作指令，保持原样，出版物中用引号包裹，网页中用行内代码标签包裹。 

```
用于 Linux 内核开发的版本控制工具。

存储在随机存取存储器（RAM）中。

通过在‘commit’命令中使用‘--interactive’或‘--patch’开关…

通过在`commit`命令中使用`--interactive`或`--patch`开关…
```

**Comment by ruanyf** [comment]
1. 英文名词按照原样书写，比如 macOS。

2. 现有文档已经做了规定。

3. 行内指令的处理，我倾向于不做硬性规定，加不加反引号由作者决定。

**Comment by xianghongai** [comment]
1. 这一条可分为多个场景：
- 英文语境普通名词，首字母大写，如 Add-ons、Cookie 这类常规词语；
- 众所周知 (Well-Known) 对象，按原样书写，如 macOS, GitHub 这类；
- 简/缩写的，全大写，如 IP, DNS 这类。
2. 是的，在〈文本/字间距〉章节。
3. 在电子排版中加，有可能某些渲染会将“代码”排版为等宽字符。

在团队中有遇到同学一律小写…
